---

# yaml-language-server: $schema=https://goreleaser.com/static/schema-pro.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

builds:
  - id: cli53
    binary: cli53
    main: ./cmd/cli53
    ldflags:
      - -s -w -X github.com/barnybug/cli53.version={{.Version}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm
      - arm64

archives:
  - id: default
    ids:
      - cli53
    formats:
      - binary
    name_template: "{{ .ProjectName }}-{{ if eq .Os \"darwin\" }}mac{{ else }}{{ .Os }}{{ end }}-{{ .Arch }}"
